version: '3.8'

services:
  app:
    image: food-recipe
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cst1supu0jms73eg5g2g-a.frankfurt-postgres.render.com:5432/food_db_s4ls
      SPRING_DATASOURCE_USERNAME: postgresm
      SPRING_DATASOURCE_PASSWORD: TCvoqFZEc1tKp5exb7VGv3voTI1EPJ7q
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
