spring:
  application:
    name: food-app
  datasource:
    url: jdbc:postgresql://localhost:5432/food_app
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
  data:
    redis:
      host: red-cst2b4hu0jms73egb3l0
      port: 6379
      timeout: 18000000ms
      database: 0
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 783571793262-08qe4hij3s74megcj45aqe2rbfngd7ft.apps.googleusercontent.com
#            client-secret: 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
#            redirect-uri: "http://95.130.227.21:8080/login/oauth2/code/google"
#            scope:
#              - email
#              - profile
#              - openid
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
my_token:
  key: abbosdevrtpkglfdsfjkjdfdsfhsdjglk
  expire_time: 2592000000


server:
  base-url : http://95.130.227.21:8080/api
  servlet:
    context-path: /api
  port: 8080
  address: 0.0.0.0

photo:
  upload:
    path  : src/main/resources/photo-uploads



springdoc:
  swagger-ui:
    operationsSorter: method


imgur:
  client-id: dfc0685027d2c8e