spring:
  application:
    name: food-app
  datasource:
    url: jdbc:postgresql://localhost:5432/food_app
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB


my_token:
  key: abbosdevrtpkglfdsfjkjdfdsfhsdjglk
  expire_time: 86400000


server:
  base-url : http://localhost:8080/api/attachment


photo:
  upload:
    path  : src/main/resources/photo-uploads


