### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "name": "ali",
  "email": "ali@com",
  "password": "root123",
  "code": "0000"
}