spring:
  application:
    name: food-app
  datasource:
    url: jdbc:postgresql://localhost:5432/food_app
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      max-file-size: 200MB
      file-size-threshold: 2KB
  data:
    redis:
      host: red-cst2b4hu0jms73egb3l0
      port: 6379
      timeout: 18000000ms
      database: 0

my_token:
  key: abbosdevrtpkglfdsfjkjdfdsfhsdjglk
  expire_time: 86400000000


server:
  base-url : http://localhost:8080/api


photo:
  upload:
    path  : src/main/resources/photo-uploads

springdoc:
  swagger-ui:
    operationsSorter: method